### ISSUE TITLE
Quoted text creates unpexpected output

### ISSUE THREAD

**Issue by jvandijk** [RonaldTreur/STSS#12]
Hey @RonaldTreur,

I hope you don't mind I keep sending in issues... I've found another one.
The following scss snippet:

``` scss
Window {
    background-color: "#2e2d2b";
    backButtonTitle: "";
    @media ios {
        navBarHidden: true;
        top: -20;
        barColor: $backgroundColor;
        barImage: '/images/transparent.png';
        hideShadow: true;
    }
}
```

Generates this TSS output:

``` json
"Window": {
        backgroundColor: "#2e2d2b",
        backButtonTitle: "\"\""
},
"Window[platform=ios]": {
        navBarHidden: true,
        top: -20,
        barColor: "#8cc63f",
        barImage: "/images/\"transparent.png\"",
        hideShadow: true
}
```

See the quoting on the `barImage` and `backButtonTitle` properties. Those references will fail to work.
