### ISSUE TITLE
Separator to camelCase only works for 1 separator

### ISSUE THREAD

**Issue by jvandijk** [RonaldTreur/STSS#13]
Hey @RonaldTreur,

In the documentation you state that you can use CSS syntax to create TSS files. This works, but not completely. See the following code snippet:

``` css
Window {
    background-color: "#2e2d2b";
    @media ios {
        nav-bar-hidden: true;
        top: -20;
        barColor: $backgroundColor;
        barImage: '/images/transparent.png';
        hideShadow: true;
    }
}
```

Mind the nav-bar-hidden syntax I used, the output is as follows:

``` json
"Window": {
        backgroundColor: "#2e2d2b"
},
"Window[platform=ios]": {
        navBar: {
                hidden: true
        },
        top: -20,
        barColor: "#8cc63f",
        barImage: "/images/\"transparent.png\"",
        hideShadow: true
}
```

It just dropped the 3rd part into a level deeper. Is that an expected behavior for other situations I don't know of... or do we need to enhance the documentation on the separator syntax?
