### ISSUE TITLE
Using @extend with existing complex structure in parent

### ISSUE THREAD

**Issue by jvandijk** [RonaldTreur/STSS#22]
Hey Ronald,

While using `@extend` I ran into an issue when extending a class that has a font definition in it.

With the following base STSS setup:
```scss
.textField {
    color: $black;
    font: {
        family: $primaryFont;
        size: $secondaryFontSize;
    }
    left: "3%";
    @media ios {
        width: "94%";
    }
    @media android {
        width: "94%";
    }
}

.textfieldWithLabel {
    @extend .textField;
    @media ios {
        width: "88%";
    }
    @media android {
        width: "88%";
    }
}
```

The TSS output is as follows, take note of the font definition:
```css
".textField": {
	color: "#000000",
	font: {
		fontFamily: "RobotoSlab-Bold",
		fontSize: "20dp"
	},
	left: "3%"
},
".textfieldWithLabel": {
	color: "#000000",
	font: "-stss-ph1",
	left: "3%"
},
".textField[platform=ios]": {
	width: "94%"
},
".textField[platform=android]": {
	width: "94%"
},
".textfieldWithLabel[platform=ios]": {
	width: "88%"
},
".textfieldWithLabel[platform=android]": {
	width: "88%"
}
```

I really don't what is going on there....
