### ISSUE TITLE
Nested object-values are misinterpreted

### ISSUE THREAD

**Issue by RonaldTreur** [RonaldTreur/STSS#6]
``` css
#header {
    backgroundGradient: {
        type: linear;
        startPoint: {
            x: 0%;
            y: 0%;
        };
        endPoint: {
            x: 0%;
            y: 100%;
        };
    };
}
```

converts to:

``` json
"#header": {
    backgroundGradient: {
        type: "linear",
        startPoint: "0%",
        endPoint: "100%"
    }
}
```
